/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import controllers.BuyingOrderController;
import models.Item;
import controllers.IDGenerator;
import java.awt.Dialog;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Category;
import models.PurchaseDetails;

/**
 *
 * @author HighSchool
 */
public class AddPurchase extends javax.swing.JFrame {
    private DefaultTableModel dtm;
    private SimpleDateFormat sdt;
    private Date date;
    /**
     * Creates new form AddItem
     */
    public AddPurchase() {
        initComponents();
        labelBuyingID.setText(new IDGenerator().GenBuyingID());
        
        sdt=new SimpleDateFormat("  YYYY/MM/dd   hh:mm:ss ");
        date=new Date();
        String s=sdt.format(date);
        labelDateTime.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCloth = new javax.swing.JPanel();
        textitemCode = new javax.swing.JTextField();
        textDescription = new javax.swing.JTextField();
        textUnitPrice = new javax.swing.JTextField();
        textQuantity = new javax.swing.JTextField();
        category1Input = new javax.swing.JTextField();
        textPurchaseDiscount = new javax.swing.JTextField();
        category2Input = new javax.swing.JTextField();
        category3Input = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableList = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonProceed = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelBuyingID = new javax.swing.JLabel();
        labelDateTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableCloth.setBackground(new java.awt.Color(255, 255, 255));

        itemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemCode.setText("Buying ID");

        textitemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textitemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textitemCodeActionPerformed(evt);
            }
        });

        Description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Description.setText("Description");

        textDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        unitPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        unitPrice.setName(""); // NOI18N
        unitPrice.setText("Unit Price");

        textUnitPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUnitPriceActionPerformed(evt);
            }
        });

        quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quantity.setText("Quantiy");

        textQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantityActionPerformed(evt);
            }
        });

        category1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        category1.setText("Category1");

        category1Input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        category1Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category1InputActionPerformed(evt);
            }
        });

        purchaseDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        purchaseDiscount.setText("Purchase Discount %");

        textPurchaseDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        category2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        category2.setText("Category2");

        category2Input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        category2Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category2InputActionPerformed(evt);
            }
        });

        category3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        category3.setText("Category3");

        category3Input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        category3Input.setText(" ");
        category3Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category3InputActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        tableList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item Code", "Description", "Unit price", "Quantity", "Purchase Dis", "Category1", "Category2", "Category"
            }
        ));
        jScrollPane1.setViewportView(tableList);

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        buttonProceed.setText("Proceed");
        buttonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProceedActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        itemCode1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemCode1.setText("Item Code");

        labelBuyingID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelBuyingID.setText(" ");

        labelDateTime.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout tableClothLayout = new javax.swing.GroupLayout(tableCloth);
        tableCloth.setLayout(tableClothLayout);
        tableClothLayout.setHorizontalGroup(
            tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tableClothLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableClothLayout.createSequentialGroup()
                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(category1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tableClothLayout.createSequentialGroup()
                                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tableClothLayout.createSequentialGroup()
                                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(category1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(tableClothLayout.createSequentialGroup()
                                                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(category2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tableClothLayout.createSequentialGroup()
                                        .addComponent(textUnitPrice)
                                        .addGap(121, 121, 121)
                                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)))
                                .addGap(13, 13, 13)
                                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(tableClothLayout.createSequentialGroup()
                                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(category2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(tableClothLayout.createSequentialGroup()
                                                .addComponent(category3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(category3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(tableClothLayout.createSequentialGroup()
                                                .addComponent(purchaseDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textPurchaseDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(textDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(tableClothLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(tableClothLayout.createSequentialGroup()
                                        .addComponent(labelBuyingID, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(162, 162, 162)
                                        .addComponent(labelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(219, 219, 219))
                                    .addGroup(tableClothLayout.createSequentialGroup()
                                        .addComponent(textitemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(587, 587, 587))))))
                    .addGroup(tableClothLayout.createSequentialGroup()
                        .addComponent(itemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tableClothLayout.createSequentialGroup()
                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(tableClothLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        tableClothLayout.setVerticalGroup(
            tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableClothLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableClothLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBuyingID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableClothLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableClothLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemCode1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(tableClothLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textitemCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textPurchaseDiscount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textUnitPrice))
                .addGap(11, 11, 11)
                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableClothLayout.createSequentialGroup()
                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(category1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(category2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(category3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableClothLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(category1Input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(category3Input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableClothLayout.createSequentialGroup()
                        .addComponent(category2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(tableClothLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonProceed, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tableCloth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUnitPriceActionPerformed

    private void textQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityActionPerformed

    private void category3InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category3InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category3InputActionPerformed

    private void category1InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category1InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category1InputActionPerformed

    private void textitemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textitemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textitemCodeActionPerformed

    private void category2InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category2InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category2InputActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        if (tableList.getSelectedRow() != -1) {
            double amount = Double.parseDouble(tableList.getValueAt(tableList.getSelectedRow(), 4).toString());
            dtm.removeRow(tableList.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row !");
        }
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        int isDispose=JOptionPane.showConfirmDialog(rootPane, "You are about to exit. Are you sure? ", "Exit", JOptionPane.WARNING_MESSAGE);
        if(isDispose==0){
            this.dispose();
        }
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        Item item=new Item(textitemCode.getText(),textDescription.getText(), Double.parseDouble(textUnitPrice.getText()));
        Category category=new Category(textitemCode.getText(),category1Input.getText(), category2Input.getText(), category3Input.getText());
        PurchaseDetails purchaseDetails=new PurchaseDetails(textitemCode.getText(),labelBuyingID.getText(), Double.parseDouble(textPurchaseDiscount.getText()),Integer.parseInt(textQuantity.getText()), Double.parseDouble(textUnitPrice.getText()));
        
        dtm=(DefaultTableModel) tableList.getModel();
        
        Object [] rowData={item.getItemCode(),item.getDescription(),item.getUnitPrice(),purchaseDetails.getQuantity(),purchaseDetails.getPurchaseDiscount(),category.getCategory1(),category.getCategory2(),category.getCategory3()};
        dtm.addRow(rowData);
        JOptionPane.showMessageDialog(rootPane, "Item added to list!", "Item Table", 2);
        
        textitemCode.setText("");
        textDescription.setText("");
        textUnitPrice.setText("");
        textitemCode.setText("");
        textQuantity.setText("");
        category1Input.setText("");
        category2Input.setText("");
        category3Input.setText("");
        
        
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProceedActionPerformed
        
        ArrayList<PurchaseDetails> purchaseDetailList = new ArrayList<>();
        ArrayList<Item> itemList = new ArrayList<>();
        for (int i = 0; i < tableList.getRowCount(); i++) {
            
            // Adding purchasedetails on tableList in to an ArrayList
            PurchaseDetails PurchaseDetails = new PurchaseDetails(
                    tableList.getValueAt(i, 0).toString(),labelBuyingID.getText(),
                    Double.parseDouble(tableList.getValueAt(i, 4).toString()),
                    Integer.parseInt(tableList.getValueAt(i, 3).toString()),
                    Double.parseDouble(tableList.getValueAt(i, 2).toString())
            );
            purchaseDetailList.add(PurchaseDetails);
            
            Item item = new Item(
                    tableList.getValueAt(i, 0).toString(),
                    tableList.getValueAt(i, 1).toString(),
                    Double.parseDouble(tableList.getValueAt(i, 2).toString())
            );
            itemList.add(item);
        }
        /*
        public Item(String itemCode, String description, double unitPrice) {
            this.itemCode = itemCode;
            this.description = description;
            this.unitPrice = unitPrice;
        }

         public PurchaseDetails(String itemCode, String buyingId, double purchaseDiscount, int quantity, double unitPrice) {
            this.itemCode = itemCode;
            this.buyingId = buyingId;
            this.purchaseDiscount = purchaseDiscount;
            this.quantity = quantity;
            this.unitPrice = unitPrice;
        }
        
        */ 
        try {
            boolean isItemAdded = BuyingOrderController.addBuyingOrder(null, purchaseDetailList, itemList);
            if (isItemAdded) {
                JOptionPane.showMessageDialog(this, "Purchase Detail saved successfully!");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Purchase Detail saved fail!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddPurchase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final java.awt.Label Description = new java.awt.Label();
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonProceed;
    private javax.swing.JButton buttonRemove;
    private final java.awt.Label category1 = new java.awt.Label();
    private javax.swing.JTextField category1Input;
    private final java.awt.Label category2 = new java.awt.Label();
    private javax.swing.JTextField category2Input;
    private final java.awt.Label category3 = new java.awt.Label();
    private javax.swing.JTextField category3Input;
    private final java.awt.Label itemCode = new java.awt.Label();
    private final java.awt.Label itemCode1 = new java.awt.Label();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuyingID;
    private javax.swing.JLabel labelDateTime;
    private final java.awt.Label purchaseDiscount = new java.awt.Label();
    private final java.awt.Label quantity = new java.awt.Label();
    private javax.swing.JPanel tableCloth;
    private javax.swing.JTable tableList;
    private javax.swing.JTextField textDescription;
    private javax.swing.JTextField textPurchaseDiscount;
    private javax.swing.JTextField textQuantity;
    private javax.swing.JTextField textUnitPrice;
    public javax.swing.JTextField textitemCode;
    private final java.awt.Label unitPrice = new java.awt.Label();
    // End of variables declaration//GEN-END:variables
}
